[Calendar][CALBE-2290][Feat] added whitelist for illegal values in pa…
ProtonMail/vobject pull request #87
Opened 2023-06-16 06:50 UTC by chris-szu

…rameter

2023-06-16 07:30 UTC, giuseppe-arcuti requested changes

2023-06-16 07:30 UTC, giuseppe-arcuti commented on tests/VObject/InvalidValueParamTest.php
> +        $this->assertEquals("LOCATION:ERROR\r\n", $doc->VEVENT->LOCATION->serialize());
```suggestion
            LOCATION;VALUE=ERROR:EXAMPLE
            SEQUENCE:0
            STATUS:CONFIRMED
            SUMMARY:AG MP3
            UID:0171706E-00F4-4846-8B5F-7FBD474A90AC
            END:VEVENT
            END:VCALENDAR
            ICS;

        $doc = Reader::read($event);
        $this->assertEquals("LOCATION:EXAMPLEr\n", $doc->VEVENT->LOCATION->serialize());
```

Just to make clearer in the test what this surgery is actually doing :)

2023-06-16 07:34 UTC, giuseppe-arcuti approved these changes

2023-06-19 04:07 UTC, liurxliu approved these changes

2023-06-19 04:53 UTC, merged